[package]
name = "prd"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
zip = "0.6.6"
serde = "1"
serde_derive = "1"
serde_json = "1"
regex = "1.4"